name: Go CI Build and Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, 1.18.x]
        platform: [ubuntu-20.04]

    runs-on: ${{ matrix.platform }}

    steps:

      - name: Install go
        uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@master

      - name: Install golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run
