name: Go CI Build and Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-18.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
      - name: Build code
        run: make build
